// app/layout.js
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./saga-redux/redux/provider";
import SessionProviders from "./components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(
    process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET,
    process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
    process.env.NEXT_PUBLIC_GITHUB_CLIENT_SECRET
  );
  return (
    <SessionProviders>
      <html lang="en">
        <body className={inter.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </SessionProviders>
  );
}
